language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

script: ./gradlew assemble


deploy:
  - provider: script
#  provider: bintray
#  file: "Path to a descriptor file, containing information for the Bintray upload"
#  user: "Bintray user"
#  key: "Bintray API key"
#  passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
  skip_cleanup: true
  on:
    all_branches: true
  dry_run: true
