on:
  push:
    branches:
      - master
    paths:
      - gradle/**
  pull_request:
    branches:
      - master
    paths:
      - gradle/**

name: Validate Gradle Wrapper

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1